### ISSUE TITLE
Spirograph

### ISSUE THREAD

**Issue by charleyburt** [charleyburt/Research_Fractals#13]
I think I found some nice [spirograph code](https://gist.github.com/alvesjnr/1948754) that should work for us. I messed around with it for about 5 minutes and already saw some pretty cool results (shown below). So, moving forward, I should just graph a whole bunch of these and then run them through our width process?

<img width="576" alt="screen shot 2017-10-23 at 2 31 57 pm" src="https://user-images.githubusercontent.com/24375139/31909323-62322028-b7ff-11e7-8741-db50de4d03ba.png">
<img width="573" alt="screen shot 2017-10-23 at 2 30 17 pm" src="https://user-images.githubusercontent.com/24375139/31909336-685ba6cc-b7ff-11e7-900d-5985d246ba81.png">
<img width="561" alt="screen shot 2017-10-23 at 2 29 29 pm" src="https://user-images.githubusercontent.com/24375139/31909345-6dd342e0-b7ff-11e7-91c2-cb5dbe477712.png">
<img width="597" alt="screen shot 2017-10-23 at 2 28 30 pm" src="https://user-images.githubusercontent.com/24375139/31909352-6fdd5a30-b7ff-11e7-8daf-f887ccf3467c.png">

**Comment by kwilliams42** [comment]
Yes, with the note that "running through the width process" might not be as easy as it seems. Does the spirograph code provide a way to sample points as it draws?

**Comment by kwilliams42** [comment]
And after reading the code for 10 seconds, I see this is easy....

**Comment by kwilliams42** [comment]
Reminder that I can only meet at our regular time (215) until about 225.
